name: 'Get .env'
description: 'Recover .env from secrets'
# inputs:
  # env-base64:  # id of input
  #   description: 'Who to greet'
  #   required: true
  #   default: 'World'
# outputs:
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo ${{ secrets.TEST }}
      shell: bash
      
