name: 'Get .env'
description: 'Recover .env from secrets'
inputs:
  env-base64: 
    description: 'Base64 encoded .env file'
    required: true
  output-path:
    description: 'Output path for .env'
    default: './.env'
# outputs:
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.env-base64 }} > ${{ inputs.output-path }}
      shell: bash
      
