name: Get Extension Version
on: 
  workflow_call:
    inputs:
      check-no-same-version: 
        type: boolean
        description: 'if true, then the version of extension must not equal to previous version.' 
    outputs:
      version:
        description: 'version of extension'
        value: ${{ jobs.get-and-validate-version.outputs.version }}

jobs:
  get-and-validate-version:
  # We ignore the case of initial commit or no manifest.json in this job :P
    env:
      MANIFEST: "./manifest.json"
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install jq

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - id: next-version
        run: echo version=$(jq -r < ${{ env.MANIFEST }} ".version") > $GITHUB_OUTPUT

      - run: git checkout HEAD^
      - id: prev-version
        run: echo version=$(jq -r < ${{ env.MANIFEST }} ".version") > $GITHUB_OUTPUT

      - if: | 
          ${{ !inputs.check-no-same-version }} ||
          ${{ steps.next-version.outputs.version == steps.prev-version.outputs.version }}
        uses: actions/github-script@v7
        env: 
          VERSION: ${{ steps.next-version.outputs.version }}
        with:
          script: |
              core.setFailed('Version ${{ env.VERSION }} already released.')    
    outputs: 
      version: ${{ steps.next-version.outputs.version }}