
on:
  push

jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::warning file=manifest.json,line=10,col=5::Code formatting issues detected"
      - uses: actions/checkout@v4
      - run: "diff manifest.json README.md"
      - id: get-version
        uses: ./.github/actions/get-extension-version
        with: 
          manifest: manifest.json

      - run: echo ${{ steps.get-version.outputs.version }}


