name: Update Chrome Extension

on:
  push:
    branches:
      - "production"

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt install jq
      - run: jq < manifest.json ".version"