name: Test

on:
  push:
    branches:
      - "production"

jobs:
  get-and-validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - id: echo-1
        uses: "./.github/workflows/echo-1.yaml"
      - run: echo ${{ steps.echo-1.outputs.result }}

