name: Test

on: pull_request
  # push:
  #   branches:
  #     - "production"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.id }}
      - run: echo ${{ github.event.pull_request.issue_url }}
      

