name: Test

# on: pull_request
on: push
  # push:
  #   branches:
  #     - "production"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: echo ${{ github.event.pull_request.id }}
      # - run: echo ${{ github.event.pull_request.issue_url }}
      - uses: ./.github/actions/get-env
        
      

