name: Update PR

on: 
  pull_request:
    branches: main
    types: ['opened', 'reopened', 'synchronize', 'closed']
# on: push
  # push:
  #   branches:
  #     - "production"

jobs:
  update-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If not closed, then update body
      - if: ${{ github.event.action != 'closed' }} 
        run: pip install PyGithub
      - if: ${{ github.event.action != 'closed' }}
        run: python3 update_pr.py
        env: 
          TOKEN: ${{ github.token }}
          PR: ${{ github.event.pull_request.number }}

      # For merged event
      - run: echo ${{ github.event.action }}
        
      

