name: Update PR

on: 
  pull_request:
    branches: main
# on: push
  # push:
  #   branches:
  #     - "production"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install PyGithub
      - run: python3 update_pr.py
        env: 
          TOKEN: ${{ github.token }}
          PR: ${{ github.event.pull_request.number }}
        
      

